music/urls.py
from django.conf.urls import url
from . import views

app_name='music'

urlpatterns = [
    #/music/
    url(r'^$', views.index, name = 'index'), #urls mappings
    #/music/album.id/
    url(r'^(?P<album_id>[0-9]+)/$', views.detail, name='detail'),
]

website/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),  # urls mappings
    url(r'^music/', include('music.urls')),  # urls mappings
]

music/models.py
from django.db import models

# Create your models here
# it's a blueprint for data base, it consists of the classes

class Album(models.Model):
    artist = models.CharField(max_length=250)
    album_title = models.CharField(max_length=500)
    genre = models.CharField(max_length=100)
    album_logo = models.CharField(max_length=1000)

    def __str__(self):
        return self.album_title + ' - '+ self.artist

class Song(models.Model):
    album = models.ForeignKey(Album, on_delete=models.CASCADE)
    file_type = models.CharField(max_length=10)
    song_title = models.CharField(max_length=250)

    def __str__(self):
        return self.song_title

music/views.py
from django.shortcuts import render, get_object_or_404
#from django.http import HttpResponse
from .models import Album
from django.http import Http404

# Create your views here.
# takes the request from user and gives mostly websites

def index(request):
    all_albums = Album.objects.all()
    return render(request, 'music/index.html', {'all_albums': all_albums})

def detail(request, album_id):
    album = get_object_or_404(Album, pk=album_id)
    return render(request, 'music/detail.html', {'album' :album })

music/templates/music/detail.html
<img src="{{album.album_logo}}" height="200" width="200">

<h1>{{album.artist}}</h1>

<h3>{{album.album_title}}</h3>

<ul>
    {% for song in album.song_set.all %}
    <li>
        {{song.song_title}} - {{song.file_type}}
    </li>
    {% endfor %}
</ul>

music/templates/music/index.html
{% if all_albums %}
    <h3>Here are my albums:</h3>
    <ul>
        {% for album in all_albums %}
        <li><a href="{% url 'music:detail' album.id %}"> {{album.album_title}} </a></li>
        {% endfor %}
    </ul>
{% else %}
    <h3> You don't have any albums to display</h3>
{%endif%}